name: sfit_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: 2.1.1
  dio: 5.1.2
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.7.0
  toggle_switch: ^2.1.0
  font_awesome_flutter: ^10.4.0
  syncfusion_flutter_pdfviewer: ^19.1.69-beta
  syncfusion_flutter_signaturepad: ^19.4.56
  fluttertoast: ^8.2.2
  another_flushbar: ^1.12.30
  http: ^0.13.5
  intl: ^0.18.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
     - assets/images/

